//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -march=armv8.6-a+bf16 -O3
// source: ../c/matmul_neon_bf16_arm64.c

TEXT ·matmul_neon_bf16(SB), $0-48
	MOVD a+0(FP), R0
	MOVD b+8(FP), R1
	MOVD c+16(FP), R2
	MOVD pm+24(FP), R3
	MOVD pn+32(FP), R4
	MOVD pk+40(FP), R5
	WORD $0xf9400068   // ldr	x8, [x3]
	WORD $0xf9400089   // ldr	x9, [x4]
	WORD $0xf100051f   // cmp	x8, #1
	WORD $0xfa41a928   // ccmp	x9, #1, #8, ge
	BLT  BB0_12
	WORD $0xf94000aa   // ldr	x10, [x5]
	WORD $0xf100015f   // cmp	x10, #0
	BLE  BB0_8
	WORD $0xd280000b   // mov	x11, #0                         ; =0x0
	WORD $0xd37ff92c   // lsl	x12, x9, #1
	WORD $0xd37ef52d   // lsl	x13, x9, #2
	WORD $0xd37ff94e   // lsl	x14, x10, #1

BB0_3:
	WORD $0xd280000f // mov	x15, #0                         ; =0x0
	WORD $0x9b097d70 // mul	x16, x11, x9
	WORD $0x8b100450 // add	x16, x2, x16, lsl #1
	WORD $0xaa0103f1 // mov	x17, x1

BB0_4:
	WORD $0xd2800003 // mov	x3, #0                          ; =0x0
	WORD $0x6f00e400 // movi.2d	v0, #0000000000000000
	WORD $0xaa0003e4 // mov	x4, x0
	WORD $0xaa1103e5 // mov	x5, x17

BB0_5:
	WORD $0x3cc04481 // ldr	q1, [x4], #4
	WORD $0xfd4000a2 // ldr	d2, [x5]
	WORD $0xfc6c68a3 // ldr	d3, [x5, x12]
	WORD $0x6e180462 // mov.d	v2[1], v3[0]
	WORD $0x2e40fc00 // bfdot
	WORD $0x91000863 // add	x3, x3, #2
	WORD $0x8b0d00a5 // add	x5, x5, x13
	WORD $0xeb0a007f // cmp	x3, x10
	BLT  BB0_5
	WORD $0x0ea16800 // bfcvtn.4h	v0, v0
	WORD $0xd37ff9e3 // lsl	x3, x15, #1
	WORD $0xfc236a00 // str	d0, [x16, x3]
	WORD $0x910011ef // add	x15, x15, #4
	WORD $0x91002231 // add	x17, x17, #8
	WORD $0xeb0901ff // cmp	x15, x9
	BLT  BB0_4
	WORD $0x9100056b // add	x11, x11, #1
	WORD $0x8b0e0000 // add	x0, x0, x14
	WORD $0xeb08017f // cmp	x11, x8
	BNE  BB0_3
	B    BB0_12

BB0_8:
	WORD $0xd280000a // mov	x10, #0                         ; =0x0
	WORD $0xd37ff92b // lsl	x11, x9, #1
	WORD $0x2f00e400 // movi	d0, #0000000000000000

BB0_9:
	WORD $0xd280000c // mov	x12, #0                         ; =0x0
	WORD $0xaa0203ed // mov	x13, x2

BB0_10:
	WORD $0xfc0085a0 // str	d0, [x13], #8
	WORD $0x9100118c // add	x12, x12, #4
	WORD $0xeb09019f // cmp	x12, x9
	BLT  BB0_10
	WORD $0x9100054a // add	x10, x10, #1
	WORD $0x8b0b0042 // add	x2, x2, x11
	WORD $0xeb08015f // cmp	x10, x8
	BNE  BB0_9

BB0_12:
	RET
