//go:build !noasm && arm64
// Code generated by GoAT. DO NOT EDIT.
// versions:
// 	clang   21.1.8
// 	objdump 2.45.1
// flags: -march=armv8.2-a+fp16 -O3
// source: ../c/matmul_blocked_f16_arm64.c

package asm

import "unsafe"

//go:noescape
func blocked_matmul_neon_f16(a, b, c, pm, pn, pk unsafe.Pointer)
